#!/usr/bin/env fish
# You need:
# - fish (https://fishshell.com/) (You don't need to use it as your shell, but it's a good shellscripting language)
# - gh - github cli (https://cli.github.com)
# - jq (https://stedolan.github.io/jq/)

set ORG $1

set repos (gh repo list $ORG --limit 9999 --json name)
set repos_to_clone (echo $repos | jq -r ".[].name")

echo "cloning repos:\n $repos_to_clone"
for u in $repos_to_clone
	echo "cloning $u"
	gh repo clone $ORG/$u; or echo "failed to clone $u"
	sleep 5
end
