#!/usr/bin/env bash

default_branch_type="feature"

if [[ $# -eq 0 ]]; then
    echo "usage: git new [feature_type] feature_name"
    exit 1
fi

if [[ $# -gt 1 ]]; then
    branch_name="$1/$2"
else
    branch_name="$default_branch_type/$1"
fi

git update-master && git checkout -b "$branch_name"
