#!/usr/bin/env bash

MAIN_BRANCHES=(master main)

for BRANCH in $MAIN_BRANCHES
do
  if git rev-parse --verify "origin/$BRANCH" > /dev/null; then
    git fetch origin && git checkout "origin/${BRANCH}" && git place-master
    exit 0
  fi
done
