#!/bin/bash

alias dco="docker-compose"
alias dce="docker-compose exec"
alias k="kubectl"
alias kx="kubectx"
alias kn="kubens"
alias ka="kube-attach"

# List all files colorized in long format
alias ll='ls -lh'

# List all files colorized in long format, including dot files
alias la="ls -lha"

# List only directories
alias lsd='ls -l | grep "^d"'

# Pretty print the path
alias path='echo $PATH | tr -s ":" "\n"'

alias -g take='| grep'

#mkdir and cd
function mkcd() { mkdir -p "$@" && cd "$_"; }

# emacs
alias emacs-mac='open -a /Applications/Emacs.app --args '
