#!/bin/bash

alias dco="docker-compose"
alias dce="docker-compose exec"

# List all files colorized in long format
alias ll='ls -lh'

# List all files colorized in long format, including dot files
alias la="ls -lha"

# List only directories
alias lsd='ls -l | grep "^d"'

# Pretty print the path
alias path='echo $PATH | tr -s ":" "\n"'

alias -g take='| grep'

#mkdir and cd
function mkcd() { mkdir -p "$@" && cd "$_"; }

#AWS login
alias aws-docker-login='eval $(aws ecr get-login --no-include-email --region eu-central-1 --profile saml)'
alias aws-only-login='python ~/Projects/tools/awsAuthentication.py'

aws-login(){ aws-only-login $1; aws-docker-login }

# emacs
alias emacs-mac='open -a /Applications/Emacs.app --args '
